/**
[test]
reason = "Lowering rejection: path variable declarations are not lowerable in v1."

[test.results]
parsing-error = '''
Path variables are not supported yet
  --> [15:7]
   |
15 | MATCH p = (a:person)-[:knows]->(b:person) RETURN a
   |       ^
'''
*/

MATCH p = (a:person)-[:knows]->(b:person) RETURN a
