/**
[test]
reason = "Lowering rejection: optional path factors are not lowerable in v1."

[test.results]
parsing-error = '''
The `?` quantifier is not supported yet
  --> [15:28]
   |
15 | MATCH (a:person)-[:knows]->?(b:person) RETURN a
   |                            ^
'''
*/

MATCH (a:person)-[:knows]->?(b:person) RETURN a
